### ISSUE TITLE
Add flight lookup widget.

### ISSUE THREAD

**Issue by pedramamini** [pedramamini/meaghanandneema.com#1]
Use Momondo flight weidget:

http://www.momondo.com/content/programmes/flightwidget/

**Comment by pedramamini** [comment]
@ofzza is this an easy one for you to do or would you like me to prep this first?

**Comment by alexclemensua** [comment]
@ofzza @pedramamini the markup is ready and pushed

**Comment by ofzza** [comment]
What exactly should I use for destination?
Can you open the Momondo flight widget, search for destination you want and paste it here?

**Comment by ofzza** [comment]
Also, what should the initial departure and return dates be and should they be editable?

**Comment by neemaamini** [comment]
Juraj: Destination is Liberia (LIR), Costa Rica

In their javascript widget generator, it appears they use that airport code (LIR)

Initial departure should be Thursday, 7/21, and departure should be Monday, 7/25. They should be editable though.

**Comment by ofzza** [comment]
I've set the destination to be locked to LIR, but there doesn't seem to be a way to set default selections for departure or return dates - dumb I know, but that is how the widget was written ...
I'll look into it some more, but if I don't find a way people will just have to select their own travel dates.

**Comment by neemaamini** [comment]
Don't worry about it too much, you guys have put in more than enough work. I don't think it's a big deal for people to just enter in the correct dates, if it takes too much work to have more proximate defaults.

**Comment by neemaamini** [comment]
The flight widget shows up in Safari, doesn't show up in Chrome.

**Comment by neemaamini** [comment]
Figured this out: it's Adblock. I don't think there is anything you can do to get around that, though I may be wrong.
