### ISSUE TITLE
Add RSVP form.

### ISSUE THREAD

**Issue by pedramamini** [pedramamini/meaghanandneema.com#4]

**Comment by neemaamini** [comment]
In the section that gives hotel info, I will need to update the phone numbers. 

For the Andaz, this is the phone number: + (506) 26901234
The Andaz will also provide a URL in a few days, so people can book the block rate rooms online

Four Seasons, I will provide soon

Thanks

**Comment by pedramamini** [comment]
@ofzza is this an easy one for you to do or would you like me to prep this first?

**Comment by neemaamini** [comment]
Excellent, as long as fonts and all that are set, I'll update the copy.

Shea will have a "Thank you" pop up image ready by tonight, so we can use a placeholder for the time being.

**Comment by ofzza** [comment]
Any news on that "Thank you" image?

**Comment by neemaamini** [comment]
She's working on something now, should have it done in a few hours. She had originally suggested just replacing the content of the form with the "Thank You" text which ,if simple enough, works. If not, she'll have the image in a few hours.
