### ISSUE TITLE
E-mail Hosting

### ISSUE THREAD

**Issue by pedramamini** [pedramamini/meaghanandneema.com#9]

**Comment by neemaamini** [comment]
Need to upload this HTML file to root for google verification. 
[google67122d4f9db51f26.html.zip](https://github.com/pedramamini/meaghanandneema.com/files/151743/google67122d4f9db51f26.html.zip)

**Comment by neemaamini** [comment]
I finished this. E-mail address is "us@meaghanandneema.com"
